export const UPDATE_PRODUCT_ATTRIBUTE_INFO = 'UPDATE_PRODUCT_INFO'

export const UPDATE_CAR_SERIES_VEHICLE_INFO = 'UPDATE_CAR_SERIES_VEHICLE_INFO'

export const UPDATE_CURRENT_ATTRIBUTE_INFO_PAGE ='UPDATE_CURRENT_ATTRIBUTE_INFO_PAGE'

export const UPDATE_CAE_SERIES_VEHICLE_PAGE = 'UPDATE_CAE_SERIES_VEHICLE_PAGE'