export const MODI_ACTIVE_PATH = 'MODI_ACTIVE_PATH'

export const UPDATE_PRODUCT_ATTRIBUTE_INFO = 'UPDATE_PRODUCT_ATTRIBUTE_INFO'

export const MODI_PRODUCT_ATTRIBUTE_INFO ='MODI_PRODUCT_ATTRIBUTE_INFO'



export const UPDATE_CAR_SERIES_VEHICLE_INFO = 'UPDATE_CAR_SERIES_VEHICLE_INFO'

export const UPDATE_CURRENT_ATTRIBUTE_INFO_PAGE ='UPDATE_CURRENT_ATTRIBUTE_INFO_PAGE'


export const UPDATE_CAE_SERIES_VEHICLE_PAGE = 'UPDATE_CAE_SERIES_VEHICLE_PAGE'
export const GET_ALL_CAR_SERIES = 'GET_ALL_CAR_SERIES'
export const ADD_CAR_SERIES_VEHICLE_INFO = 'ADD_CAR_SERIES_VEHICLE_INFO'



export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
export const ADD_PRODUCT_INFO　='ADD_PRODUCT_INFO'
export const MODI_PRODUCT_INFO = 'MODI_PRODUCT_INFO'
export const DELETE_PRODUCT_INFO = 'DELETE_PRODUCT_INFO'